### ISSUE TITLE
my system become kali

### ISSUE THREAD

**Issue by Cherkah** [LionSec/katoolin#111]
hi guys

my os was debian 9. 
i have upgraded  my system with kali repo: now i'm on kali!
i haven't saw from the issues any kind of info about recovering system.

so just tell me how can i recover my debian? (reinstall or bootlaoder or grub ...)

regards

**Comment by Atavic** [comment]
1) *Add Kali repositories & Update*

3) *Remove all kali linux repositories*

**Comment by Atavic** [comment]
Hit 1 *Add Kali repositories & Update*

    Hit 3 *Remove all kali linux repositories*

**Comment by Cherkah** [comment]
ok, thanks
issue close
