### ISSUE TITLE
the public key is not available

### ISSUE THREAD

**Issue by Cyberhan123** [LionSec/katoolin#137]
I change the kali public key Server  by:keyserver.ubuntu.com but it doesn't work.
who can help me ,Thanks

![Uploading 3951358-a7a0d782514f6cca.png…]()

Hit:1 http://mirrors.aliyun.com/ubuntu bionic InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu bionic-security InRelease
Hit:3 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease
Hit:4 http://mirrors.aliyun.com/ubuntu bionic-proposed InRelease
Hit:5 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease
Get:6 http://mirrors.aliyun.com/kali kali-rolling InRelease [30.5 kB]
Err:6 http://mirrors.aliyun.com/kali kali-rolling InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ED444FF07D8D0BF6
Reading package lists... Done
W: GPG error: http://mirrors.aliyun.com/kali kali-rolling InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ED444FF07D8D0BF6
E: The repository 'http://mirrors.aliyun.com/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by renaudg-dev** [comment]
Hi, you can try to comment the line 49 of the katoolin.py setup script and save them.
after:
sudo wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add

sudo apt-get update

sudo katoolin

katoolin > 1 (for repo menu)
>1 (for add repo)
>2 (for update repos)

after you can install your wanted tools.
it works on my Ubuntu 18.

hoping to have helped you
and please excuse me for my english level ;)

**Comment by serenityit2018** [comment]
Good evening,

@Cyberhan123 i tried your solution, but i got the same error message.

What do you want to do ?> 1
Executing: /tmp/apt-key-gpghome.IWpav2r2lI/gpg.1.sh --keyserver pgp.mit.edu --recv-keys ED444FF07D8D0BF6
gpg: key ED444FF07D8D0BF6: 1 duplicate signature removed
gpg: key ED444FF07D8D0BF6: 142 Beglaubigungen wegen fehlender Schlüssel nicht geprüft
gpg: Schlüssel ED444FF07D8D0BF6: "Kali Linux Repository <devel@kali.org>" nicht geändert
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 1
gpg:              unverändert: 1

It seems that the key is not valid anymore. Is there an alternative for Katoolin or another solution?

Thx

**Comment by VikasAmbrale** [comment]
I tried replacing the public keyServer from "pgp.mit.edu" to "pool.sks-keyservers.net" and it worked perfectly. For this open katoolin.py file in read and write mode and replace the keyserver (line 49)   "pgp.mit.edu" to "pool.sks-keyservers.net" and run the katoolin.

hope this helps.

**Comment by Mightyb0x** [comment]
@VikasAmbrale

Thanks that worked! 👍

**Comment by Cyberhan123** [comment]
@VikasAmbrale 
Thanks this worked, I think this issues can be close.

**Comment by chrsjhnsn** [comment]
@VikasAmbrale's fix doesn't work for me. Still getting `gpg: keyserver receive failed: Server indicated a failure`.

**Comment by Cyberhan123** [comment]
@chrsjhnsn U can uninstall and reload,it may help

**Comment by BlackWolf95** [comment]
Hi everybody,
I tried installing Katoolin and faced the same problem. I changed the content in line 49 as indicated but still getting the same result. What's going wrong?
![screenshot_20180811_175728](https://user-images.githubusercontent.com/34475532/43993595-32dfb2f0-9d90-11e8-95ec-a651efa06d0b.png)

**Comment by juandisouza** [comment]
> I tried replacing the public keyServer from "pgp.mit.edu" to "pool.sks-keyservers.net" and it worked perfectly. For this open katoolin.py file in read and write mode and replace the keyserver (line 49) "pgp.mit.edu" to "pool.sks-keyservers.net" and run the katoolin.
> 
> hope this helps.

how can i open katoolin.py in read and write mode?

**Comment by Ronexlemon** [comment]
replace the "pools.sks-keyservers.net"   with "pgp.mit.edu" and it works perfectly
