### ISSUE TITLE
problem with installing katoolin on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by overlord1741** [LionSec/katoolin#155]
![123](https://user-images.githubusercontent.com/42696326/44618559-f553f300-a880-11e8-8e19-6b2deff82d03.png)
pliz help

**Comment by TheUnable** [comment]
Try ./katoolin.py

**Comment by Super-Gil** [comment]
same issue here!

**Comment by reaper439** [comment]
You must completely remove the katoolin directories before attempting to reinstall after a botched install.

Try code below and attempt to install again.

'rm -rf ~/katoolin

sudo rm /usr/bin/katoolin`
