### ISSUE TITLE
Not installed on Ubuntu 16.04

### ISSUE THREAD

**Issue by sublimecyrax** [LionSec/katoolin#19]
When I add kali repository on Ubuntu 16.04, I get the error: key 7D8D0BF6: public key "Kali Linux Repository <devel@kali.org>" not found. And installation all tools an error: The following packages have unmet dependencies:  acccheck : Depends: smbclient but it is not going to be installed  enum4linux : Depends: samba but it is not going to be installed 
Depends: smbclient but it is not going to be installed 
E: Unable to correct problems, you have held broken packages. Also there was an error about the unstable version my Ubuntu.﻿

**Comment by K3223th** [comment]
I'm having the same issues.

**Comment by kd4pba** [comment]
Pretty much same boat here.  For 16.04 I am not sure how there would not be mismatches. All three major pen testing distros are way behind IMO.  Not sure this is the authors fault.  I don't' see the PPA's aligning with 16.04 any time soon, even if they do I expect a few things to be broken. If this is a no go for too long i may just dual boot Blackarch.

**Comment by GeorgeGorelishvili** [comment]
after installing on Ubuntu 16.04 stable windows content fills black area, and also can be deleted katoolin environment. when will stable Katoolin version on ubuntu 16.04?

**Comment by batvanko66** [comment]
I had the same issue and rebooted in recovery mode(hit Shift after BIOS) then used the option for the Grub(tried the other options but I think it was the GRUB that fixed it) then rebooted and all was back to normal with all of the Kali tools available in my classicmenu. hope this helps
