### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by ve4k** [LionSec/katoolin#203]
I am running Ubuntu 19.04 and i want to uninstall all kali linux tools.

**Comment by gilgongo** [comment]
Unfortunately, you'll need to manually remove them with apt I think.

**Comment by Advenk** [comment]
Are you looking to remove the script or the tools installed? You can find alot of entries in /usr/share. 
use sudo rm -r <tool name>. Be careful in this directory!

**Comment by bc140400159** [comment]
i think in fedora, this command is work for me,
rm -r katoolin
-r is remove step by step
on each iteration you have to press Y and next simple

**Comment by tonywtrd** [comment]
> i think in fedora, this command is work for me,
> 
> rm -r katoolin
> 
> -r is remove step by step
> 
> on each iteration you have to press Y and next simple

`$ rm` command will only delete a file or a folder if you add the recursive (-r) option as `$ rm -r`  which can be replaced by `$ rm -rf ~/DIR` to prevent triggering of the confirmation to delete each file.

But this will definitely not delete tools installed by Katoolin which use package manager. Actually, Katoolin are literaly a kind on package manager for Kali Tool.
