### ISSUE TITLE
Missing packages in debian-testing

### ISSUE THREAD

**Issue by Jeeppler** [LionSec/katoolin#21]
Kalilinux is based on debian testing, but there are still three missing packages:
- dff
- ntop
- webshag

![debian-8-testing-kali](https://cloud.githubusercontent.com/assets/2007739/15200022/eefcd0dc-17a8-11e6-953e-81808cf8614a.png)

I am not sure if this is an Katoolin issue or a Kalilinux issue.

**Comment by Hades1996** [comment]
I'm getting this issue too, on ubuntu 16.04

**Comment by anzx42** [comment]
Ubuntu 14.04 getting this issue
