### ISSUE TITLE
Ubuntu 20.04 became kali/gnu linux

### ISSUE THREAD

**Issue by raj22700** [LionSec/katoolin#244]
So i installed katoolin and then i got a massive upgrade which when i did my ubuntu became kali/gnu linux. Any solution if available

**Comment by keithsavage777** [comment]
sudo: unable to execute /usr/bin/katoolin: No such file or directory". Thanks for the great resource and the help. is all the error i am getting. at lest your got intstalled can u help boss

**Comment by agoyel25** [comment]
i fixed this problem its very simple!
**sudo git clone katoolin** in your home directory after that use this command
**sudo cp katoolin/katoolin.py /usr/bin/katoolin** this will copy katoolin to usr/bin
after that go to /usr/bin and type **sudo chmod +x katoolin** and after that **sudo python2 katoolin**
i hope this i shoing to fix the issue

**Comment by mendyz** [comment]
Worked. On Ubuntu 20.04 on wsl 2

**Comment by raj22700** [comment]
I had to clean install ubuntu again to remove it.

**Comment by reteps** [comment]
Fixed by rewriting `/etc/os-release` with my correct Ubuntu version.

https://askubuntu.com/questions/1280557/how-to-revert-damage-done-by-editing-etc-os-release
