### ISSUE TITLE
gpg: keyserver receive failed: No name

### ISSUE THREAD

**Issue by Synv-09** [LionSec/katoolin#289]
i'm trying to install katoolin3 on ubuntu 20.04 but i get the following error
root@sy:/home/synv/katoolin3# ./install.sh 
Executing: /tmp/apt-key-gpghome.1W0b3PytX0/gpg.1.sh -qq --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6
gpg: keyserver receive failed: No name
Executing: /tmp/apt-key-gpghome.j54UFnCqaJ/gpg.1.sh -qq --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys ED444FF07D8D0BF6
gpg: keyserver receive failed: No name
This may be a server issue. Please try again later

please help me fix that, thanks everyone.

**Comment by IvanNULP** [comment]
The same problem... Can somebody help us?

**Comment by xstp** [comment]
Try the following command:
`% wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add`

if this succeeds, comment out the following line in Katoolin.py

`cmd1 = os.system("apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6")`

**Comment by emalgamatedsoy** [comment]
would it be a good idea to replace the os.system() command with
(wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add)
cmd1 = os.system("apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6")
so that 
cmd1 = os.system("wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add")

I tested it in the python 2.7.x interpreter on xubuntu xfce 18.04 and was able to get a return code of 0 and an stdout of "OK"

**Comment by xstp** [comment]
Yes. Don't forget to also update the package lists.

**Comment by chuck1497** [comment]
Who's this

**Comment by FlubOtic** [comment]
I'm having the same problem. I don't want to manually download each tool, someone fix it plz :(

**Comment by cclliu9333** [comment]
> would it be a good idea to replace the os.system() command with
> (wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add)
> cmd1 = os.system("apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6")
> so that
> cmd1 = os.system("wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add")
> 
> I tested it in the python 2.7.x interpreter on xubuntu xfce 18.04 and was able to get a return code of 0 and an stdout of "OK"

I have the following error running the above.

quote:
Warning:  apt-key is deprecated.  Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
E:  This command can only be used by root.
unquote:

what should I do?

**Comment by shift-tab** [comment]
After this command succeeds:
'''sudo wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add'''

Open up "install.sh" located in the Katoolin folder using a text editor (sudo vi install.sh) and comment out the line that begins with:
'''#apt-key adv -qq'''

Then again try running '''sudo ./install.sh". Katool install should succeed.

**Comment by eaglegoboom** [comment]
yep same issue, cant update, upgrade nothing with that no valid OpenPGP data

**Comment by Sentaku67** [comment]
Use this line : 
`sudo wget -q -O - https://archive.kali.org/archive-key.asc | gpg --dearmor  | sudo apt-key add`
instead of : 
`sudo wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add`



> After this command succeeds: `sudo wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add`
> 
> open up "install.sh" located in the Katoolin folder using a text editor (sudo vi install.sh) and comment out (add #) the line that begins with:

**Comment by kalistamp** [comment]
> I'm having the same problem. I don't want to manually download each tool, someone fix it plz :(

Hey Could i ask you a Favor, Could you briefly explain how i would possibly download the tools manually as i only need a few of them and i am also recieving the errror after running "sudo ./install.sh"

" gpg: keyserver receive failed: Server indicated a failure
This may be a server issue. Please try again later "

**Comment by Daniel-Pms** [comment]
Am i the only one who does not see a file called installed.sh ???

**Comment by dragoscosma** [comment]
for katoolin3 do this and it will work:
- open install.sh
- edit the line starting with: apt-key and paste this: apt-key adv -qq --keyserver keyserver.ubuntu.com --recv-keys ED444FF07D8D0BF6 || apt-key adv -qq --keyserver hkp://keyservers.ubuntu.com:80 --recv-keys ED444FF07D8D0BF6 || die "This may be a server issue. Please try again later";
- now go to the terminal and run this: chmod +x ./install.ch
- and finally run: sudo ./install.sh

**Comment by Lupupam** [comment]
many thanks dragoscosma......definetlyworks,,,bravo

**Comment by onsleji** [comment]
> for katoolin3 do this and it will work:
> 
> * open install.sh
> * edit the line starting with: apt-key and paste this: apt-key adv -qq --keyserver keyserver.ubuntu.com --recv-keys ED444FF07D8D0BF6 || apt-key adv -qq --keyserver hkp://keyservers.ubuntu.com:80 --recv-keys ED444FF07D8D0BF6 || die "This may be a server issue. Please try again later";
> * now go to the terminal and run this: chmod +x ./install.ch
> * and finally run: sudo ./install.sh

Great Help!!!
