### ISSUE TITLE
Error on 8th line

### ISSUE THREAD

**Issue by LRCaetanoM** [LionSec/katoolin#337]
Dears, you've made a mistake on line 8 on 'katoolin.py', try oppening and closing a comma at the print function.
![error](https://user-images.githubusercontent.com/95530995/202808682-4579426c-fd7e-472c-8ae1-c77c75d9afc4.png)

**Comment by sa7mon** [comment]
Line 8 doesn't need any commas. If you mean parentheses, it doesn't need any of those either because this tool is written in Python2

**Comment by zennvoan12** [comment]
> Dears, you've made a mistake on line 8 on 'katoolin.py', try oppening and closing a comma at the print function. ![error](https://user-images.githubusercontent.com/95530995/202808682-4579426c-fd7e-472c-8ae1-c77c75d9afc4.png)

so bro u must use sysmbol () that's will be work

**Comment by ojasmessi** [comment]
where comma?

**Comment by LRCaetanoM** [comment]
I'm so sorry people. English is my second language and yes, it doesn't need neither comma or parenthesis because it was written in python 2, not 3. I apologize for the mistake
