### ISSUE TITLE
Print Statement Syntax Error

### ISSUE THREAD

**Issue by CHEGEBB** [LionSec/katoolin#362]
Description: The script contains a syntax error in the print statement.
Error Message: SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)
Solution: Update the print statement in katoolin.py from print "Sorry. This script requires sudo privileges" to print("Sorry. This script requires sudo privileges").

**Comment by sukuna969** [comment]
solution
run katoolin by command :
python2 katoolin.py

**Comment by CHEGEBB** [comment]
Nice this was helpful

**Comment by DrTemperance** [comment]
no.
