### ISSUE TITLE
Ubuntu 16.04 Compatibility

### ISSUE THREAD

**Issue by hahagu** [LionSec/katoolin#45]
After installing all kali tools on ubuntu 16.04 and rebooting, unity does not start.
However, if you use gnome desktop instead of unity, you will get the same issue, except that when you go into the terminal ( Ctrl + Alt + F1 ), and type 'startx' into the terminal after login, gnome will start.
Please fix this problem.
Thank-you.

**Comment by pscom** [comment]
In my case it install grub and i cannot use my ubuntu with unity... Grub is set on terminal and show me "Kali GNU/Linux Rolling". How can I fix it?

**Comment by hahagu** [comment]
While there are a few methods to fix this,
for example, remove kali repositories, remove & purge grub, and reinstall grub.
What I want to know is, how you got the tools working.
