### ISSUE TITLE
Unable to install All categories at the same time

### ISSUE THREAD

**Issue by f1r3walled** [LionSec/katoolin#55]
Hello,
I have used your tool before and it's amazing but now it just presented an error to me.
When I open the "2) View Categories" and choose "0) All" I'm receiving an error (unable to located jd, yara...).
I took a quickly look at your katoolin.py script and there are some error referring to JD-GUI, Yara and some Reverse engineering tools installastion through apt-get. In your script it's wrote only jd, YARA, Valgrind... and for sure the repositories won't find it.

Just to let you know! Thx by your tool and help!

**Comment by SuperSuperSuperSuper5** [comment]
Maybe you should add non-free and main repositories
