### ISSUE TITLE
chmod +x /usr/bin/katoolin - No such file or directory

### ISSUE THREAD

**Issue by ionakathryn** [LionSec/katoolin#77]
Hi so I am reaching this point in the process and file / dir can't be located when I run this command. How to solve this?

Thanks

**Comment by ionakathryn** [comment]
I solved it by doing:

sudo cp katoolin/katoolin.py /usr/bin/katoolin

I think it is something to not having correct access rights however before installing i ran:

sudo su

So I don't know why it didn't work, but it works now!

**Comment by Jay991** [comment]
I'm having exactly the same issue. I running on a remote server could that be the issue?

**Comment by julerobb1** [comment]
cp: cannot stat 'katoolin/katoolin.py': No such file or directory
root@troop59:/home/webmaster/katoolin# 
 is the message i get.

**Comment by coder-board** [comment]
It's your python's version that hold the key. Update your python to 3.0 then maybe can solve the issue.
