### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ohdude** [LionSec/katoolin#8]
I get this error

gqrx : Vereisten: libgnuradio-analog3.7.5 Will not be installed
        Vereisten: libgnuradio-blocks3.7.5 Will not be installed
        Vereisten: libgnuradio-fft3.7.5 Will not be installed
        Vereisten: libgnuradio-filter3.7.5 Will not be installed
        Vereisten: libgnuradio-osmosdr0.1.3 Will not be installed
        Vereisten: libgnuradio-pmt3.7.5 Will not be installed
        Vereisten: libgnuradio-runtime3.7.5 Will not be installed
 winexe : Vereisten: samba-libs (= 2:4.1.17+dfsg-2kali1) but 2:4.1.17+dfsg-4ubuntu3 Will not be installed

**Comment by azarax** [comment]
Could you please try with Ubuntu 15.04. I've had the same problem with Ubuntu 15.10 and solved the problem when I tried to Ubuntu 15:04. I think there is a mismatch and katoolin no package is not compatible with Ubuntu 15.10.

**Comment by sourcekris** [comment]
FYI I have installed on multiple Ubuntu 15.10's now (standard build + Ubuntu MATE) and I have had success just by removing winexe and gqrx packages from the katoolin script. The conflict seems to be with the samba-libs package. 

While these two tools do serve a purpose, overall the benefit of having the other tools in a Ubuntu environment outweighs missing these two packages.

**Comment by ohdude** [comment]
I close this issue because I did not tested it anymore
